

const dummyData = [
  {
    activity: "Login",
    operation: "Access",
    companyName: "Alpha Corp",
    user: "john.doe@example.com",
    period: "N/A",
    dateTime: "2024-06-29 09:00 AM",
  },
  {
    activity: "GSTR1 Upload",
    operation: "Create",
    companyName: "Beta LLC",
    user: "jane.smith@example.com",
    period: "APR-2024",
    dateTime: "2024-06-29 10:15 AM",
  },
  {
    activity: "Company Profile Update",
    operation: "Update",
    companyName: "Gamma Inc",
    user: "admin@example.com",
    period: "N/A",
    dateTime: "2024-06-29 11:30 AM",
  },
  {
    activity: "GSTR3B Download",
    operation: "Read",
    companyName: "Delta Solutions",
    user: "user123@example.com",
    period: "MAR-2024",
    dateTime: "2024-06-29 01:00 PM",
  },
  {
    activity: "User Deactivation",
    operation: "Delete",
    companyName: "Epsilon Enterprises",
    user: "admin@example.com",
    period: "N/A",
    dateTime: "2024-06-29 02:45 PM",
  },
  {
    activity: "Login Attempt (Failed)",
    operation: "Access",
    companyName: "Omega Group",
    user: "invalid.user@example.com",
    period: "N/A",
    dateTime: "2024-06-29 03:00 PM",
  },
  {
    activity: "GSTR1 Correction",
    operation: "Update",
    companyName: "Phoenix Co.",
    user: "john.doe@example.com",
    period: "FEB-2024",
    dateTime: "2024-06-28 09:30 AM",
  },
  {
    activity: "New Company Creation",
    operation: "Create",
    companyName: "Titan Industries",
    user: "admin@example.com",
    period: "N/A",
    dateTime: "2024-06-28 10:45 AM",
  },
  {
    activity: "Logout",
    operation: "Access",
    companyName: "Aurora Systems",
    user: "jane.smith@example.com",
    period: "N/A",
    dateTime: "2024-06-28 05:00 PM",
  },
  {
    activity: "GSTR3B Upload",
    operation: "Create",
    companyName: "Nebula Innovations",
    user: "user123@example.com",
    period: "MAY-2024",
    dateTime: "2024-06-27 01:20 PM",
  },
  {
    activity: "Download Audit Log",
    operation: "Read",
    companyName: "Orion Solutions",
    user: "admin@example.com",
    period: "N/A",
    dateTime: "2024-06-27 09:00 AM",
  },
  {
    activity: "Password Change",
    operation: "Update",
    companyName: "Zenith Corp",
    user: "john.doe@example.com",
    period: "N/A",
    dateTime: "2024-06-26 11:00 AM",
  },
  {
    activity: "Account Activation",
    operation: "Update",
    companyName: "Apex Dynamics",
    user: "admin@example.com",
    period: "N/A",
    dateTime: "2024-06-26 02:00 PM",
  },
  {
    activity: "GSTR1 Preview",
    operation: "Read",
    companyName: "Quantum Labs",
    user: "jane.smith@example.com",
    period: "JUN-2024",
    dateTime: "2024-06-25 03:30 PM",
  },
];


export default dummyData;