

const dummyData = [
  // {
  //   srNo: 1,
  //   fileName: "GSTR1_Apr2024_ABC_Pvt_Ltd.json",
  //   returnType: "GSTR1",
  //   period: "APR-2024",
  //   status: "Processed",
  //   successCount: 150,
  //   failCount: 0,
  //   downloadFile: "download-link-1.json",
  //   checkSheet: "check-sheet-link-1.pdf",
  //   dateTime: `2024-05-10 10:30 AM`,
  // },
  // {
  //   srNo: 2,
  //   fileName: "GSTR3B_Mar2024_XYZ_Traders.xlsx",
  //   returnType: "GSTR3B",
  //   period: "MAR-2024",
  //   status: "Failed",
  //   successCount: 80,
  //   failCount: 5,
  //   downloadFile: "download-link-2.xlsx",
  //   checkSheet: "check-sheet-link-2.pdf",
  //   dateTime: "2024-04-20 02:15 PM",
  // },
  // {
  //   srNo: 3,
  //   fileName: "GSTR1_May2024_PQR_Enterprises.csv",
  //   returnType: "GSTR1",
  //   period: "MAY-2024",
  //   status: "Pending",
  //   successCount: 0,
  //   failCount: 0,
  //   downloadFile: "N/A", // No download yet
  //   checkSheet: "N/A", // No check sheet yet
  //   dateTime: "2024-06-01 09:00 AM",
  // },
  // {
  //   srNo: 4,
  //   fileName: "GSTR9_FY2023_LMN_Services.zip",
  //   returnType: "GSTR9",
  //   period: "FY2023",
  //   status: "Processed",
  //   successCount: 200,
  //   failCount: 0,
  //   downloadFile: "download-link-3.zip",
  //   checkSheet: "check-sheet-link-3.pdf",
  //   dateTime: "2024-04-15 11:00 AM",
  // },
  // {
  //   srNo: 5,
  //   fileName: "GSTR3B_Apr2024_ABC_Pvt_Ltd.json",
  //   returnType: "GSTR3B",
  //   period: "APR-2024",
  //   status: "Processed with Errors",
  //   successCount: 145,
  //   failCount: 2,
  //   downloadFile: "download-link-4.json",
  //   checkSheet: "check-sheet-link-4.pdf",
  //   dateTime: "2024-05-25 04:00 PM",
  // },
  // {
  //   srNo: 6,
  //   fileName: "GSTR1_Jun2024_XYZ_Traders.json",
  //   returnType: "GSTR1",
  //   period: "JUN-2024",
  //   status: "Pending",
  //   successCount: 0,
  //   failCount: 0,
  //   downloadFile: "N/A",
  //   checkSheet: "N/A",
  //   dateTime: "2024-06-28 01:00 PM",
  // },
  // {
  //   srNo: 7,
  //   fileName: "GSTR1_Jul2024_PQR_Enterprises.csv",
  //   returnType: "GSTR1",
  //   period: "JUL-2024",
  //   status: "Processed",
  //   successCount: 90,
  //   failCount: 0,
  //   downloadFile: "download-link-5.csv",
  //   checkSheet: "check-sheet-link-5.pdf",
  //   dateTime: "2024-08-05 09:45 AM",
  // },
  // {
  //   srNo: 8,
  //   fileName: "GSTR3B_May2024_LMN_Services.xlsx",
  //   returnType: "GSTR3B",
  //   period: "MAY-2024",
  //   status: "Failed",
  //   successCount: 75,
  //   failCount: 10,
  //   downloadFile: "download-link-6.xlsx",
  //   checkSheet: "check-sheet-link-6.pdf",
  //   dateTime: "2024-06-18 03:30 PM",
  // },
  // {
  //   srNo: 9,
  //   fileName: "GSTR9C_FY2023_ABC_Pvt_Ltd.zip",
  //   returnType: "GSTR9C",
  //   period: "FY2023",
  //   status: "Processed",
  //   successCount: 1,
  //   failCount: 0,
  //   downloadFile: "download-link-7.zip",
  //   checkSheet: "check-sheet-link-7.pdf",
  //   dateTime: "2024-04-22 10:00 AM",
  // },
  // {
  //   srNo: 10,
  //   fileName: "GSTR1_Aug2024_XYZ_Traders.json",
  //   returnType: "GSTR1",
  //   period: "AUG-2024",
  //   status: "Pending",
  //   successCount: 0,
  //   failCount: 0,
  //   downloadFile: "N/A",
  //   checkSheet: "N/A",
  //   dateTime: "2024-09-01 11:00 AM",
  // },
  // {
  //   srNo: 11,
  //   fileName: "GSTR3B_Jun2024_PQR_Enterprises.json",
  //   returnType: "GSTR3B",
  //   period: "JUN-2024",
  //   status: "Processed",
  //   successCount: 110,
  //   failCount: 0,
  //   downloadFile: "download-link-8.json",
  //   checkSheet: "check-sheet-link-8.pdf",
  //   dateTime: "2024-07-10 01:00 PM",
  // },
  // {
  //   srNo: 12,
  //   fileName: "GSTR1_Sep2024_LMN_Services.csv",
  //   returnType: "GSTR1",
  //   period: "SEP-2024",
  //   status: "Processed with Errors",
  //   successCount: 98,
  //   failCount: 1,
  //   downloadFile: "download-link-9.csv",
  //   checkSheet: "check-sheet-link-9.pdf",
  //   dateTime: "2024-10-05 08:30 AM",
  // },
  // {
  //   srNo: 13,
  //   fileName: "GSTR3B_Jul2024_ABC_Pvt_Ltd.xlsx",
  //   returnType: "GSTR3B",
  //   period: "JUL-2024",
  //   status: "Pending",
  //   successCount: 0,
  //   failCount: 0,
  //   downloadFile: "N/A",
  //   checkSheet: "N/A",
  //   dateTime: "2024-08-18 02:45 PM",
  // },
  // {
  //   srNo: 14,
  //   fileName: "GSTR1_Oct2024_XYZ_Traders.json",
  //   returnType: "GSTR1",
  //   period: "OCT-2024",
  //   status: "Processed",
  //   successCount: 130,
  //   failCount: 0,
  //   downloadFile: "download-link-10.json",
  //   checkSheet: "check-sheet-link-10.pdf",
  //   dateTime: "2024-11-03 10:15 AM",
  // },
  // {
  //   srNo: 15,
  //   fileName: "GSTR3B_Aug2024_PQR_Enterprises.csv",
  //   returnType: "GSTR3B",
  //   period: "AUG-2024",
  //   status: "Failed",
  //   successCount: 60,
  //   failCount: 8,
  //   downloadFile: "download-link-11.csv",
  //   checkSheet: "check-sheet-link-11.pdf",
  //   dateTime: "2024-09-12 04:00 PM",
  // },
  // {
  //   srNo: 16,
  //   fileName: "GSTR1_Nov2024_LMN_Services.json",
  //   returnType: "GSTR1",
  //   period: "NOV-2024",
  //   status: "Pending",
  //   successCount: 0,
  //   failCount: 0,
  //   downloadFile: "N/A",
  //   checkSheet: "N/A",
  //   dateTime: "2024-12-01 09:30 AM",
  // },
  // {
  //   srNo: 17,
  //   fileName: "GSTR3B_Sep2024_ABC_Pvt_Ltd.xlsx",
  //   returnType: "GSTR3B",
  //   period: "SEP-2024",
  //   status: "Processed",
  //   successCount: 165,
  //   failCount: 0,
  //   downloadFile: "download-link-12.xlsx",
  //   checkSheet: "check-sheet-link-12.pdf",
  //   dateTime: "2024-10-20 01:50 PM",
  // },
  // {
  //   srNo: 18,
  //   fileName: "GSTR1_Dec2024_XYZ_Traders.json",
  //   returnType: "GSTR1",
  //   period: "DEC-2024",
  //   status: "Processed with Errors",
  //   successCount: 120,
  //   failCount: 3,
  //   downloadFile: "download-link-13.json",
  //   checkSheet: "check-sheet-link-13.pdf",
  //   dateTime: "2025-01-05 11:20 AM",
  // },
  // {
  //   srNo: 19,
  //   fileName: "GSTR3B_Oct2024_PQR_Enterprises.csv",
  //   returnType: "GSTR3B",
  //   period: "OCT-2024",
  //   status: "Failed",
  //   successCount: 70,
  //   failCount: 7,
  //   downloadFile: "download-link-14.csv",
  //   checkSheet: "check-sheet-link-14.pdf",
  //   dateTime: "2024-11-15 03:10 PM",
  // },
  // {
  //   srNo: 20,
  //   fileName: "GSTR1_Jan2025_LMN_Services.json",
  //   returnType: "GSTR1",
  //   period: "JAN-2025",
  //   status: "Pending",
  //   successCount: 0,
  //   failCount: 0,
  //   downloadFile: "N/A",
  //   checkSheet: "N/A",
  //   dateTime: "2025-02-01 09:00 AM",
  // },
];


export default dummyData;